    package com.safeguard.ui.education

import java.util.Calendar

/**
 * Rotating cybersecurity tips for non-technical users. Index changes each calendar day.
 */
object CyberSecurityAwarenessFacts {

    val facts: List<String> = listOf(
        "📱 Installing apps from random websites or chat links can skip safety checks you get from official stores.",
        "📦 An APK is an app package—if it is from an unknown source, you cannot be sure what is inside.",
        "🎭 Some fake apps copy the icon and name of a popular app so closely they look real at a glance.",
        "🦠 Malware can hide inside apps that seem harmless, like simple games or wallpaper tools.",
        "🎁 A “free premium” paid app is often a trap that may steal data or flood you with ads.",
        "🔗 Phishing links in texts often use short links so you cannot see the real site until too late.",
        "🏦 Real banks rarely text you to “verify” your password or PIN—those messages are often scams.",
        "🎭 Social engineering means tricking people—attackers may pretend to be a friend, boss, or support.",
        "⏱️ If someone rushes you to act “right now,” they often do not want you to think.",
        "🔐 Risky apps sometimes ask for permissions that do not match what the app claims to do.",
        "🔦 A flashlight app should not need your contacts or text messages.",
        "📍 Turning off location for apps you do not trust can reduce how much of your routine is tracked.",
        "📶 Public Wi‑Fi is handy, but others on the same network may see traffic that is not protected.",
        "☕ A fake “Free Wi‑Fi” hotspot can be set up just to watch what people type.",
        "📡 Using mobile data for banking is often safer than random public Wi‑Fi.",
        "📂 Data theft on phones can include photos, messages, and saved passwords if malware or a thief gets in.",
        "🆔 Identity theft can start with small details—those answers are often used for security questions.",
        "⚠️ Fake “system update” pop-ups on websites try to scare you into installing junk.",
        "⚙️ Real Android updates come through Settings, not through a random browser download.",
        "📲 Side-loading an APK means installing outside the store—only do it if you fully trust the source.",
        "⏳ Some malware waits quietly and only activates later to avoid suspicion.",
        "🔋 Unusual battery drain or heat can sometimes mean hidden apps are busy in the background.",
        "📊 A sudden jump in data use may mean something is uploading without your knowledge.",
        "🔒 Locking your phone with a PIN, pattern, or fingerprint is a simple shield if it is lost.",
        "⏲️ Auto-lock after a short time reduces the chance someone reads your apps off a lost phone.",
        "🏪 Downloading from official stores lowers—but does not remove—the risk of harmful software.",
        "⭐ Even store apps deserve a quick check: recent reviews, update dates, and the developer name.",
        "💬 Malicious links in chats can look like a photo, coupon, or “voice message” preview.",
        "🏦 Banking malware may show a fake login on top of the real bank app to steal credentials.",
        "🎙️ Spyware can abuse microphone or camera in extreme cases—another reason to review permissions.",
        "🚫 “Monitor your partner” apps are invasive and often illegal to use without their consent.",
        "🔑 Reusing one password everywhere means one leak can unlock many accounts.",
        "🧩 A passphrase of random words can be easier to remember and stronger than a short messy password.",
        "🗝️ Use a trusted password manager to generate and store complex passwords securely.",
        "🔄 Change your passwords immediately if you suspect they have been compromised.",
        "🔢 Two-factor authentication helps even if your password is stolen—thieves still need the second step.",
        "📲 SMS codes for login are better than nothing; app codes or security keys are often stronger.",
        "🌐 Criminals buy leaked passwords from old breaches and try them on many sites.",
        "📩 “Smishing” is phishing by SMS—fake delivery texts are a common trick.",
        "▢ QR codes in public can send you to bad sites—only scan codes you trust.",
        "📞 Fake support numbers in search results can connect you to scammers, not the real company.",
        "📺 App clones may show ads that pay criminals while you think you use the real app.",
        "💸 Some bad apps sign you up for paid services or premium texts to drain money.",
        "🔐 Ransomware is famous on PCs; phones can rarely be locked or files encrypted too.",
        "📢 Adware floods ads—it may not steal passwords, but it slows the phone and hurts privacy.",
        "🐴 Trojans look helpful but hide harmful code inside.",
        "🪱 Worms spread on their own—more common on networks than in typical phone installs.",
        "📜 Early experiments with self-copying programs in the 1970s–1980s inspired what people later called “viruses.”",
        "📰 The term “computer virus” spread widely in the 1980s as programs copied like germs.",
        "📱 Early phone viruses targeted simpler devices—today’s threats are far more advanced.",
        "🤖 Android’s flexibility means users should be careful what they install.",
        "🚪 “Unknown sources” lets manual installs—it is a door to open only when necessary.",
        "👆 Screen overlay tricks can make you tap “Allow” on a permission you did not mean to give.",
        "🛠️ Review app permissions in Settings and take back access the app no longer needs.",
        "📋 Clipboard data can include copied passwords—some malware reads the clipboard.",
        "🔔 Notifications can hide phishing text—read the full sender name before tapping.",
        "🎭 Voice scams may use fake voices—verify urgent money requests through a known number.",
        "🎁 Gift cards are a favorite scam because they are hard to reverse—real firms rarely demand them.",
        "₿ Crypto transfers are also hard to undo—scammers love them for the same reason.",
        "💕 Dating scams often move you to another chat app quickly to avoid safety tools.",
        "💼 Fake job offers may ask for upfront fees or bank details—real employers rarely do that early.",
        "📦 Fake parcel texts are built to make you tap before you notice the link is wrong.",
        "📡 Bluetooth off when unused slightly reduces risk in crowded places.",
        "👶 Kids’ devices need the same care—children may tap ads and install without reading.",
        "🕰️ Old apps that never update may have known holes criminals can use.",
        "🗑️ Uninstall apps you do not use—less risk and more storage.",
        "🖼️ Screenshots of chats can leak sensitive info if shared or backed up carelessly.",
        "☁️ Cloud photo backup is handy—protect that account with a strong unique password.",
        "📲 SIM swap moves your number to a thief’s SIM—strong account recovery options help.",
        "✉️ Email on your phone is a common phishing entry—treat surprise links like strangers at the door.",
        "📅 Spam calendar invites can contain phishing links—decline and delete odd entries.",
        "👥 Games that ask for contacts “to find friends” deserve a second thought before you allow.",
        "❤️‍🩹 Health and fitness apps may collect sensitive data—check privacy text before you agree.",
        "🌐 Free VPNs sometimes sell browsing data—paid reputable services often spell out policy more clearly.",
        "🔒 HTTPS (the lock) encrypts traffic to that site—it does not mean the business is honest.",
        "🔤 Typos in web addresses (look-alike names) fool people who read too fast.",
        "🎬 Deepfakes can fake video—verify urgent money requests another way.",
        "🔌 Public USB charging can, in theory, carry data risks—your own cable and adapter are safer.",
        "📍 Find My Device helps locate or erase a lost phone—turn it on before you need it.",
        "🛡️ Encrypting phone storage (often on by default) helps if the device is lost.",
        "🔔 Lock-screen notifications can leak OTP codes—consider hiding sensitive previews when locked.",
        "🖥️ Screen sharing during support can expose passwords—watch what is visible.",
        "👀 “Shoulder surfing” is someone watching you type your PIN—cover the keypad in public.",
        "♿ Malware sometimes asks for Accessibility—powerful for accessibility, dangerous if abused.",
        "⭐ Sort app reviews by “most recent” to spot sudden scam or ad complaints.",
        "❓ Huge download counts but almost no reviews can be a warning sign.",
        "🕸️ Cybercrime is organized—some groups focus on phishing, others on bank fraud.",
        "📋 Stolen login lists are sold—unique passwords limit how far one leak spreads.",
        "❓ Security questions with public answers are weak—use random answers stored safely.",
        "🔄 Multi-device sync is convenient—log out of old devices you no longer use.",
        "✈️ Travelers are targeted more—fatigue and new Wi‑Fi make people click faster.",
        "🧩 Social quizzes that ask “your first car” can match security question answers.",
        "📍 Turning off precise location on social apps reduces real-time tracking misuse.",
        "📝 Store 2FA backup codes on paper—not only as a screenshot in your gallery.",
        "👨‍👩‍👧 Family accounts need strong recovery—one weak password can expose everyone.",
        "💬 Kids’ games with chat can expose them to strangers—use parental controls if you can.",
        "💰 Some scams start with a tiny fake “refund” to build trust before the big ask.",
        "🔄 Updates fix security bugs—delaying them leaves known holes open longer.",
        "🆕 “Zero-day” means a flaw the vendor does not know yet—updates still fix everything else.",
        "📦 Sandboxing isolates apps, but risky permissions and mistakes still matter.",
        "🧪 If your phone acts odd after a new install, uninstall that app first and see if it stops.",
        "🔄 Factory reset removes many threats—back up first, then restore only what you trust.",
        "📣 Reporting scam texts helps protect others—not only you.",
        "📜 Data breach rules differ by country—companies follow local laws when leaks happen.",
        "🌍 Privacy ideas spread globally—even outside Europe, apps may follow similar practices.",
        "📖 The “what we collect” part of a privacy policy answers the important questions.",
        "📺 Opting out of personalized ads in system settings reduces some profiling—not all tracking.",
        "🎭 Dark patterns push you to agree fast—slow down and read the small text.",
        "💳 Wallet apps work best with lock screen plus biometrics together.",
        "✉️ Split-payment scams ask for part now and part later—verify with a known contact.",
        "🎙️ Voice messages add emotion—scammers use urgency on purpose.",
        "📸 Group chats spread fake news fast—one screenshot circulates before anyone checks.",
        "✈️ Airplane mode can pause unexpected data use while you check a suspicious app.",
        "🌱 Fewer accounts and apps means fewer places for thieves to strike.",
        "🏛️ National cyber agencies publish free guides for families—simple language, big impact.",
        "⏸️ The strongest habit is pausing three seconds before “Install” or “Allow.”",
        "📍 Turn on Find My Device before you lose the phone.",
        "⚠️ Pop-ups that say “your phone is infected” to sell cleaners are often fake—trust your security app or system.",
        "🎮 Modded games and cheats are a common path for malware.",
        "📡 Decline Bluetooth pairing requests from unknown devices.",
        "✉️ If email forwarding rules change oddly, your account may be compromised—check settings.",
        "✅ Good security is daily: updates, unique passwords, cautious installs, and verifying urgent requests."
    )

    fun indexForToday(): Int {
        val cal = Calendar.getInstance()
        val y = cal.get(Calendar.YEAR)
        val d = cal.get(Calendar.DAY_OF_YEAR)
        val seed = y * 400 + d
        return seed % facts.size
    }

    fun factForToday(): String = facts[indexForToday()]
}
